steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/[IMAGE_NAME]:$COMMIT_SHA', '.']

  # Run unit tests
  - name: 'gcr.io/$PROJECT_ID/[IMAGE_NAME]:$COMMIT_SHA'
    entrypoint: 'npm'
    args: ['run', 'test']
