apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: myapp
spec:
  # modify replicas according to your case
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: pchecker
        image: gcr.io/sit737-23t1-amuwala-ba-6cf3733/s222313962/pchecker:latest
        ports:
        - containerPort: 8080